#!/bin/bash
alias ls='ls --color=auto'
alias ll='ls -al'
alias gs='git status'
alias cduva='cd /home/lorian/Dropbox/UvA/'
alias cdssl='cd /home/lorian/Dropbox/SSL-Leiden/'
alias cdvia='cd /home/lorian/Dropbox/VIA/'

alias sl="sl -e"
alias LS="sl -e"
alias copy="xclip -selection c"

alias clearl="clear;ls -l"
alias wine32="WINEPREFIX=~/.wine32 wine"
alias sudo='sudo env PATH=$PATH'

alias uvavpn="sudo /opt/uvavpn/ncsvc -h uvavpn.uva.nl -u 10769153 -r users -f /opt/uvavpn/certificaat-uvavpn.der"
