#!/bin/bash
alias ls='ls --color=auto'
alias ll='ls -al'
alias grep='grep --color=auto'
alias gs='git status'
alias cduva='cd /home/lorian/Dropbox/UvA/'
alias cdssl='cd /home/lorian/Dropbox/SSL-Leiden/'
alias cdvia='cd /home/lorian/Dropbox/VIA/'

alias sl="sl -e"
alias LS="sl -e"
alias copy="xclip -selection c"

alias clearl="clear;ls -l"
alias wine32="WINEPREFIX=~/.wine32 wine"

alias uvavpn="sudo /opt/uvavpn/ncsvc -h uvavpn.uva.nl -u 10769153 -r users -f /opt/uvavpn/certificaat-uvavpn.der"

alias vimupdateplugins="vim -c PluginUpdate"
alias viminstallplugins="vim -c PluginInstall"

alias ssldeclaraties='nemo /home/lorian/Dropbox/SSL-Leiden/Declaraties & 2> /dev/null'
alias sudo='sudo -E'

alias cddotfiles="cd /home/lorian/Dropbox/dotfiles/"
alias mountstack="sudo mount -t davfs https://loriancoltof.stackstorage.com/remote.php/webdav/ /mnt/stack"

alias pls='sudo /usr/bin/zsh -c "$(fc -ln -1)"'

alias venvactivate='source venv-laptop/bin/activate.zsh'

#venvactivate() {
    #if [ -d ./venv ]; then
        #if type deactivate &> /dev/null; then
            #deactivate
        #fi
        #unlink ./venv
    #fi
    #ln -s ./venv-laptop venv
    #source ./venv/bin/activate.zsh
    #echo "Virtual environment activated"
#}

#venvdeactivate() {
    #if [ ! -d ./venv ]; then
        #echo "Virtual environment is not activated"
    #else
        #deactivate
        #unlink ./venv
        #echo "Virtual environment deactivated"
    #fi
#}
