#!/usr/bin/env python
import shutil
import subprocess
import sys


class SoundController:
    has_amixer = False

    step = 5
    currently_muted = False

    def __init__(self):
        self.has_amixer = shutil.which('alsamixer') is not None

    def switch_mute(self):
        if self.has_amixer:
            command = "amixer -q -D pulse sset Master 1+ toggle"
            subprocess.run(command.split())

    def increase_volume(self):
        if self.has_amixer:
            command = "amixer -q -D pulse sset Master %s%%+" % self.step
            subprocess.run(command.split())

    def decrease_volume(self):
        if self.has_amixer:
            command = "amixer -q -D pulse sset Master %s%%-" % self.step
            subprocess.run(command.split())

if __name__ == "__main__":
    c = SoundController()

    if sys.argv[1] == "+":
        c.increase_volume()
    elif sys.argv[1] == "-":
        c.decrease_volume()
    elif sys.argv[1] == "togglemute":
        c.switch_mute()

    subprocess.run(["pkill", "-SIGUSR1", "-f", "python3 .+/i3statusconf\.py"])
