#!/usr/bin/env python
import shutil
import subprocess
import sys

class SoundController:
    def __init__(self):
        self.has_pulseaudio_ctl = shutil.which('pulseaudio-ctl') is not None
        if not self.has_pulseaudio_ctl:
            sys.stderr.write('pulseaudio-ctl is not installed')

    def toggle_mute(self):
        if self.has_pulseaudio_ctl:
            command = "pulseaudio-ctl mute"
            subprocess.run(command.split())

    def increase_volume(self):
        if self.has_pulseaudio_ctl:
            command = "pulseaudio-ctl up"
            subprocess.run(command.split())

    def decrease_volume(self):
        if self.has_pulseaudio_ctl:
            command = "pulseaudio-ctl down"
            subprocess.run(command.split())

    def get_volume(self):
        if self.has_pulseaudio_ctl:
            command = "pulseaudio-ctl full-status"
            proc = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
            out, err = proc.communicate()
            (volume, sink_mute, _) = out.split()

            volume = int(volume.decode('utf-8'))
            sink_mute = sink_mute == b'yes'

            return (volume, sink_mute)

if __name__ == "__main__":
    c = SoundController()

    if sys.argv[1] == "up":
        c.increase_volume()
    elif sys.argv[1] == "down":
        c.decrease_volume()
    elif sys.argv[1] == "mute":
        c.toggle_mute()

    subprocess.run(["pkill", "-SIGUSR1", "-f", "python3 .+/i3statusconf\.py"])
    vol, muted = c.get_volume()
    subprocess.run("volnoti-show{} {}".format(" -m" if muted else "", vol).split())
    subprocess.run(["mplayer",
                    "/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"])

